name: Health Check

on:
    #    schedule:
    #        - cron: "0 0 * * *" # Disabled by default, uncomment to enable
    workflow_dispatch:

jobs:
    health_check:
        runs-on: ubuntu-latest
        steps:
            - name: Check main site
              uses: jtalk/url-health-check-action@v4
              with:
                  url: https://full-stack-open-pokedex-saku.fly.dev
                  follow-redirect: false
                  max-attempts: 3
                  retry-delay: 10s
                  retry-all: false

            - name: Check health endpoint
              uses: jtalk/url-health-check-action@v4
              with:
                  url: https://full-stack-open-pokedex-saku.fly.dev/health
                  follow-redirect: false
                  max-attempts: 3
                  retry-delay: 10s
                  retry-all: false

        # Simulate a failure for testing purposes

        #    - name: Check failed simulation endpoint
        #      uses: jtalk/url-health-check-action@v4
        #      with:
        #           url: https://full-stack-open-pokedex-saku.fly.dev/failed-health
        #           follow-redirect: false
        #           max-attempts: 3
        #           retry-delay: 10s
        #           retry-all: false
